const data = {
  products: [
    {
      _id: "1",
      id: "1",
      description: "כיסוי עמיד לגשם ומים למוצרי SONOFF",
      name: "CLASSERICA יומן יומי 15/21מדורג מעורב צבעים ",
      category: "office test",
      price: 700,
      image: "/images/oxford.png",
      rating: 4.7,
      countInStock: 0,
    },
    {
      _id: "2",
      id: "2",
      name: " TOUCH יומן יומי 15/21מדורג מעורב צבעים ",
      category: "office",
      description: "כיסוי עמיד לגשם ומים למוצרי SONOFF",
      price: 80,
      image: "/images/oxford.png",
      rating: 4.7,
      countInStock: 10,
    },
    {
      _id: "3",
      id: "3",
      description: "כיסוי עמיד לגשם ומים למוצרי SONOFF",
      name: " TOUCH יומן יומי 15/21מדורג מעורב צבעים ",
      category: "office",
      price: 80,
      image: "/images/oxford.png",
      rating: 4.7,
      countInStock: 10,
    },
    {
      _id: "4",
      id: "4",
      description: "כיסוי עמיד לגשם ומים למוצרי SONOFF",
      name: " TOUCH יומן יומי 15/21מדורג מעורב צבעים ",
      category: "office",
      price: 80,
      image: "/images/oxford.png",
      rating: 4.7,
      countInStock: 10,
    },

    {
      _id: "5",
      id: "5",
      description: "כיסוי עמיד לגשם ומים למוצרי SONOFF",
      name: " TOUCH יומן יומי 15/21מדורג מעורב צבעים ",
      category: "office",
      price: 80,
      image: "/images/oxford.png",
      rating: 4.7,
      countInStock: 10,
    },

    {
      _id: "6",
      id: "6",
      description: "כיסוי עמיד לגשם ומים למוצרי SONOFF",
      name: " TOUCH יומן יומי 15/21מדורג מעורב צבעים ",
      category: "office",
      price: 80,
      image: "/images/oxford.png",
      rating: 4.7,
      countInStock: 10,
    },
  ],
};

export default data;
